pethouse2/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('pet/', include('pets.urls')),
    path('appointment/', include('appointment.urls'))

    

]

pets/urls.py
from django.urls import path

from pets import views

urlpatterns = [

    path('register/<int:id>', views.RegisterPet, name='petRegister'),
    path('list/<int:id>', views.List_pet, name='petList'),
    path('update/<int:id>', views.UpdatePet, name='updatePet'),
    path('delete/<int:id>', views.DeletePet, name='deletePet'),
    path('list_all/', views.List_all_pets, name='listAllPets'),
    ]

users/urls.py
from django.urls import path
from users import views


urlpatterns = [
    path('home/', views.home, name='home'),
    path('register_user/', views.user_register, name='register_user'), 
    path('view_user/', views.user_view, name='view_user'),
    path('update_user/<int:id>', views.user_update, name='update_user'),
    path('list_user/', views.user_list, name='list_user'),
    path('delete_user/<int:id>', views.user_delete, name='delete_user'),
    path('view_specific_user/<int:id>', views.view_specific_user, name='view_specific_user'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    """Model User""" 
    cell_phone = models.CharField(max_length=50)
    address = models.CharField(max_length=255, blank=True, null=True)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    is_client = models.BooleanField(default=False)
    is_vet = models.BooleanField(default=False)
    photo = models.ImageField(upload_to='media/photos', blank=True, null=True)

users/forms.py
from django.contrib.auth.models import User 
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):

    username = forms.CharField(max_length=30, required=True, label="Username", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your Username'}))
    first_name = forms.CharField(max_length=30, required=False, label="First Name",
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your first name'}))
    last_name = forms.CharField(max_length=30, required=False, label="Last Name",
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your last name'}))
    email = forms.EmailField(required=False, label="Email",
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}))
    cell_phone = forms.CharField(label="Phone Number", widget=(forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your Phone'})))
    address = forms.CharField(label="Address", widget=(forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your Address'})))
    
    password1 = forms.CharField(label="Password", widget=(forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'})))
        
    password2 = forms.CharField(label="Confirm Password", widget=(forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm your password'})))
    

    class Meta:
        model = get_user_model()
        fields = ["username", "first_name", "last_name",
                  'email','cell_phone','address','password1', 'password2']


class UpdateForm(forms.ModelForm):
    
        username = forms.CharField(max_length=30, required=True, label="Username", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your Username'}))
        first_name = forms.CharField(max_length=30, required=False, label="First Name",
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your first name'}))
        last_name = forms.CharField(max_length=30, required=False, label="Last Name",
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your last name'}))
        email = forms.EmailField(required=False, label="Email",
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}))
        cell_phone = forms.CharField(label="Phone Number", widget=(forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your Phone'})))
       
        address = forms.CharField(label="Address", widget=(forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your Address'})))
        class Meta:
            model = get_user_model()
            fields = ["username", "first_name", "last_name",
                        'email', 'cell_phone', 'address']
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from users.models import User
from .forms import RegisterForm, UpdateForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

# Create your views here.

@login_required
def home(request):
    """
    You can show the index view in your proyect
    """
    return render(request, 'base2.html')



def user_register(request):
    """
    You can register users in your database and show the register form.
    """

    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            register_form.save()
            return redirect('login')
    else:
        register_form = RegisterForm()
    
    context = {
        'register_form': register_form
    }

    return render(request, 'users/user_register.html', context)

@login_required
def user_view(request):
    """
    You can show the user view in your proyect
    """
    return render(request, 'users/user_view.html')

@permission_required('users.change_my_user')
def user_update(request, id):
    """
    You can update the user in your proyect
    """
    update_form = None
    error = None
    status = None
    try:
        user = User.objects.get(id = id)
        if request.method == 'GET':
            update_form = UpdateForm(instance = user)
        else:
            update_form = UpdateForm(request.POST, instance = user)
            if update_form.is_valid():
                update_form.save()
            return redirect('home')
    except ObjectDoesNotExist:
        error = "Client Does not exist"
        
    context = {
        'update_form': update_form,
        'error': error,
        'status': status,
        'u': id
    }
    return render(request, 'users/user_update.html', context)



@permission_required('users.view_all_users')
def user_list(request):
    """
    You can show your clients of your database
    """
    user = User.objects.filter(is_active=True)

    context = {
        'users': user
    }

    return render(request, 'users/user_list.html', context)

@permission_required('users.delete_user')
def user_delete(request, id):
    """
    Delete a client changing his status account to False
    """
    user = User.objects.get(id = id)
    user.is_active = False
    user.save()
    return redirect('list_user')


@permission_required('users.view_user')
def view_specific_user(request, id):
    """
    You can see a client specific data
    """
    user = None
    error = None
    try:
        user = User.objects.get(id = id)
    except ObjectDoesNotExist:
        error = "Client Does not exist"

    context = {
        'item': user,
        'error': error,
    }
    return render(request, 'users/user_specific_view.html', context)

templates/users/user_list.html
{% extends 'base2.html' %}
{%load static%}

{% block tittle%} User list {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <h3 class="text-center " style="color:dimgrey "> User list</h3>
    <table class="table" id="tabla" style="border: 1px solid darkgrey;
                        border-radius: 20px; background-color:#20c997; opacity:0.9;color:#181818">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nickname</th>
                <th scope="col">FirstName</th>
                <th scope="col">LastName</th>
                <th scope="col">Email</th>
                <th scope="col">Address</th>
                <th class="text-center" scope="col">Options</th>
                
            </tr>
        </thead>
        <tbody>
            {% for u in users %}
            <tr>
                <th scope="row">{{u.id}}</th>
                <td>{{u.username}}</td>
                <td>{{u.first_name}}</td>
                <td>{{u.last_name}}</td>
                <td>{{u.email}}</td>
                <td>{{u.address}}</td>
                <td>
                    {% if perms.users.change_user%}
                    <a class="btn btn-primary" style="margin-right: 5px ;" href="{% url 'update_user' u.id %}">Edit</a>
                    {% endif %}
                    {% if perms.users.delete_user%}
                    <a class="btn btn-danger" href="{% url 'delete_user' u.id %}">Delete</a>
                    {% endif %}
                    <a class="btn btn-success" href="{% url 'view_specific_user' u.id %}">View</a>
                </td>
                

            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>

{% endblock content %}

templates/users/user_register.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block tittle%} Register {%endblock%}

{%block navbar%} {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card" id = "content-register">
                <div class="card-body">
                    <h3 class="text-center " style="color:dimgrey "> Please Register Here!</h3>
                    <hr>
                    <form method="POST">

                        {% csrf_token%}
                        {{ register_form | crispy }}

                        <input type="submit" name="submit" class="btn btn-success btn-md" value="submit">
                        <a class="btn btn-dark" href="{% url 'login'%}"> Cancel </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/users/user_specific_view.html
{%extends 'base2.html' %}


{%block tittle%}View User {%endblock%}

{% block content %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card" id="content-register">
                {%if item%}
                <div class="card-body">
                    <h2 class="text-center " style="color:dimgrey ">{{item.first_name}} {{item.last_name}}'s view</h2>
                    <hr>
                    <h3>Data User</h3>
                    <hr>
                    Username: <h4>{{item.username}}</h4>
                    <hr>
                    Email: <h4>{{item.email}}</h4>
                    <hr>
                    Phone: <h4>{{item.cell_phone}}</h4>
                    <hr>
                    Address: <h4>{{item.address}}</h4>
                    <hr>
                    <a class="btn btn-info" href="{% url 'list_user'%}"> Back </a>
                </div>
                {% endif %}
                {%if error%}
                    <h2>User doesn't exits</h2>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/users/user_update.html
{% extends 'base2.html' %}

{% load crispy_forms_tags %}

{% block tittle%} Update User {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card" id="content-register">

                {% if user.id == u or perms.users.change_user%}
                <div class="card-body">
                    
                    <h3 class="text-center " style="color:dimgrey "> Update data</h3>
                    <hr>
                    <form action="" method="POST">

                        {% csrf_token%}
                        {{ update_form | crispy }}

                        <input type="submit" name="submit" class="btn btn-success btn-md" value="submit">
                        <a class="btn btn-dark" href="{% url 'view_user'%}"> Cancel </a>
                    </form>
                </div>
                {%else%}
                    <h2>You don't have permission to this information</h2>
                {%endif%}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/users/user_view.html
{%extends 'base2.html' %}


{%block tittle%}View User {%endblock%}

{% block content %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card" id="content-register">
                <div class="card-body">
                    <h2 class="text-center " style="color:dimgrey ">Hola {{user.first_name}} {{user.last_name}}</h2>
                    <hr>
                    <h3>Mis datos</h3>
                    <hr>
                    Username: <h4>{{user.username}}</h4>
                    <hr>
                    Email: <h4>{{user.email}}</h4>
                    <hr>
                    Phone: <h4>{{user.cell_phone}}</h4>
                    <hr>
                    Address: <h4>{{user.address}}</h4>
                    <hr>
                    <a class="btn btn-success" href="{% url 'update_user' user.id%}"> Update </a>
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}